#!/bin/bash

echo "PR Review Feature Test Guide"
echo "============================"
echo ""
echo "This feature allows you to review pull request comments and automatically"
echo "send them to Claude for processing."
echo ""
echo "How to test:"
echo "1. Make sure you have an active pull request with comments"
echo "2. Run the claude-squad application"
echo "3. Create or select an instance"
echo "4. Press 'R' to open the PR review interface"
echo "5. Use the following keys in the review interface:"
echo "   - j/k or ↓/↑: Navigate between comments"
echo "   - a: Accept current comment"
echo "   - d: Deny current comment"
echo "   - A: Accept all comments"
echo "   - D: Deny all comments"
echo "   - Enter: Process accepted comments with Claude"
echo "   - q/Esc: Cancel and return"
echo ""
echo "The accepted comments will be sent to Claude one by one for processing."
echo ""
echo "Note: You need to have 'gh' CLI installed and authenticated to use this feature."